USE [master]
GO
/****** Object:  Database [MyTest]    Script Date: 8/26/2022 10:19:56 AM ******/
CREATE DATABASE [MyTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\MyTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\MyTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MyTest] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyTest] SET RECOVERY FULL 
GO
ALTER DATABASE [MyTest] SET  MULTI_USER 
GO
ALTER DATABASE [MyTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyTest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyTest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MyTest', N'ON'
GO
ALTER DATABASE [MyTest] SET QUERY_STORE = OFF
GO
USE [MyTest]
GO
/****** Object:  Table [dbo].[KetQua]    Script Date: 8/26/2022 10:19:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KetQua](
	[MaSo] [int] NOT NULL,
	[MaMH] [nchar](6) NOT NULL,
	[Diem] [int] NULL,
 CONSTRAINT [PK_KetQua] PRIMARY KEY CLUSTERED 
(
	[MaSo] ASC,
	[MaMH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Khoa]    Script Date: 8/26/2022 10:19:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Khoa](
	[MaKhoa] [nchar](6) NOT NULL,
	[TenKhoa] [nchar](30) NULL,
 CONSTRAINT [PK_Khoa] PRIMARY KEY CLUSTERED 
(
	[MaKhoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mon]    Script Date: 8/26/2022 10:19:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mon](
	[MaMH] [nchar](6) NOT NULL,
	[TenMH] [nchar](50) NULL,
	[SoTiet] [int] NULL,
 CONSTRAINT [PK_Mon] PRIMARY KEY CLUSTERED 
(
	[MaMH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SinhVien]    Script Date: 8/26/2022 10:19:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SinhVien](
	[MaSo] [int] IDENTITY(1,1) NOT NULL,
	[HoTen] [nvarchar](50) NULL,
	[NgaySinh] [datetime] NULL,
	[GioiTinh] [bit] NULL,
	[DiaChi] [nvarchar](50) NULL,
	[DienThoai] [int] NULL,
	[MaKhoa] [nchar](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KetQua]  WITH CHECK ADD  CONSTRAINT [FK_KetQua_Mon] FOREIGN KEY([MaMH])
REFERENCES [dbo].[Mon] ([MaMH])
GO
ALTER TABLE [dbo].[KetQua] CHECK CONSTRAINT [FK_KetQua_Mon]
GO
ALTER TABLE [dbo].[KetQua]  WITH CHECK ADD  CONSTRAINT [FK_KetQua_SinhVien] FOREIGN KEY([MaSo])
REFERENCES [dbo].[SinhVien] ([MaSo])
GO
ALTER TABLE [dbo].[KetQua] CHECK CONSTRAINT [FK_KetQua_SinhVien]
GO
ALTER TABLE [dbo].[SinhVien]  WITH CHECK ADD  CONSTRAINT [FK_SinhVien_Khoa] FOREIGN KEY([MaKhoa])
REFERENCES [dbo].[Khoa] ([MaKhoa])
GO
ALTER TABLE [dbo].[SinhVien] CHECK CONSTRAINT [FK_SinhVien_Khoa]
GO
USE [master]
GO
ALTER DATABASE [MyTest] SET  READ_WRITE 
GO
